// Small deterministic P3 cage fixture used by the dependency-free preview
// regressions.  Production manifests are generated by chest_deformer.py;
// this fixture keeps the runtime tests independent of Python file I/O.
export function makeP3Fixture(part) {
  const cols = 6, rows = 4;
  const bounds = [90, 100, 190, 190];
  const restPoints = [];
  for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++)
    restPoints.push([bounds[0] + (bounds[2] - bounds[0]) * c / (cols - 1),
      bounds[1] + (bounds[3] - bounds[1]) * r / (rows - 1)]);
  const keyform = (kind) => {
    const out = [];
    const yw = kind === "bust_y_pos" ? [0.05, 0.35, 1.0, 0.85]
      : kind === "bust_y_neg" ? [0.05, 0.35, 0.85, 1.0] : [0.05, 0.35, 0.9, 1.0];
    for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) {
      const t = c / (cols - 1), centered = t - 0.5;
      if (kind.startsWith("bust_y")) out.push([
        centered * 1.0 * (r >= 2 ? 1 : 0.25),
        (kind === "bust_y_pos" ? -1 : 1) * 6 * yw[r],
      ]);
      else out.push([
        (kind === "bust_x_pos" ? 1 : -1) * 6 * yw[r]
          + (kind === "bust_x_pos" ? -centered : centered) * 0.72,
        centered * 0.24 * yw[r],
      ]);
    }
    return out;
  };
  const rest = part.mesh.rest, cells = [], uv = [], influence = [];
  for (let i = 0; i < rest.length / 2; i++) {
    const gx = (rest[i * 2] - bounds[0]) / (bounds[2] - bounds[0]) * (cols - 1);
    const gy = (rest[i * 2 + 1] - bounds[1]) / (bounds[3] - bounds[1]) * (rows - 1);
    const cx = Math.max(0, Math.min(cols - 2, Math.floor(gx)));
    const cy = Math.max(0, Math.min(rows - 2, Math.floor(gy)));
    cells.push([cx, cy]); uv.push([gx - cx, gy - cy]);
    const edge = Math.min(rest[i * 2] - bounds[0], bounds[2] - rest[i * 2],
      rest[i * 2 + 1] - bounds[1], bounds[3] - rest[i * 2 + 1]);
    influence.push(Math.max(0, Math.min(1, edge / 12)));
  }
  return {
    version: 1, enabled: true, target_tag: "topwear", profile: "springy",
    parameters: { x: "ParamBustX", y: "ParamBustY" },
    ranges_px: { x: 6, y: 6 },
    cage: { cols, rows, bounds, rest_points: restPoints },
    binding: { mode: "bilinear_grid_v1", vertex_cells: cells, vertex_uv: uv,
      vertex_influence: influence, locked_vertices: influence.map((value) => value === 0) },
    keyforms: { neutral: restPoints.map(() => [0, 0]),
      bust_x_neg: keyform("bust_x_neg"), bust_x_pos: keyform("bust_x_pos"),
      bust_y_neg: keyform("bust_y_neg"), bust_y_pos: keyform("bust_y_pos") },
    locks: { upper_attachment: true, center_seam: false, occluder_aware: true },
  };
}
